### ISSUE TITLE
[feature] Web UI for Sybil 

### ISSUE THREAD

**Issue by JoeSHMOEK** [Tempor-ai/sybil#93]
## Context/Goal:
- To complete M5, we need to build and deploy a UI to the SNET Marketplace.  
- This will allow users to send in their requests in the form of JSON configuration files, and CSV formatted data.  
- The UI will be made available to customers through this page: https://beta.singularitynet.io/servicedetails/org/temporai/service/sybil

## Details:
- The DAPP sandbox can be used to test the UI against an existing SNET deployment
  - Documentation can be found here: https://github.com/singnet/snet-dapp
  - https://dev.singularitynet.io/docs/ai-developers/dapp-ui-component/
  - https://github.com/improbable-eng/grpc-web/blob/master/client/grpc-web/docs/code-generation.md
- The UI will require a reference to the sybil.proto configuration to compile.
  - sybil.proto is located here: https://github.com/Tempor-ai/sybil/blob/grpc_schema/src/appserver/sybil.proto

## Needs:
- UI Shall contain a single element for uploading either a model JSON configuration file or model YAML configuration files for the Train function: 
  - Example file contents of model JSON configuration file:
```
{
  "type": "meta_lr",
  "scorers": ["smape", "mape"],
  "params": {
      "preprocessors": [
          {"type": "dartsimputer", "params": {"strategy": "mean"}},
          {"type": "minmaxscaler"}
      ],
      "base_models": [
          {"type": "darts_naive"},
          {"type": "darts_seasonalnaive"},
          {"type": "darts_autotheta"},
          {"type": "darts_autoets"},
          {"type": "darts_autoarima"},
          {"type": "darts_tbats"},
          {"type": "darts_linearregression"}
      ]
  }
}
```
  - Example file contents of model YAML configuration file:
```
type: meta_lr
scorers: [smape, mape]
params:
  preprocessors:
    type: dartsimputer
      params:
        strategy: mean
    type: minmaxscaler
  base_models:
    type: darts_naive
    type: darts_seasonalnaive
    type: darts_autotheta
    type: darts_autoets
    type: darts_autoarima
    type: darts_tbats
    type: darts_linearregression
```
- UI Shall contain a single element for uploading CSV formatted data for the Train function:
  - Example file contents of CSV data:
```
ds,y
1949-01-01,112
1949-02-01,118
1949-03-01,132
1949-04-01,129
1949-05-01,121
1949-06-01,135
1949-07-01,148
1949-08-01,148
1949-09-01,136
1949-10-01,119
1949-11-01,104
1949-12-01,118
1950-01-01,115
1950-02-01,126
1950-03-01,141
1950-04-01,135
1950-05-01,125
1950-06-01,149
1950-07-01,170
...
```
- UI shall have its JavaScript code uploaded to [Tempor-ai/sybil ](https://github.com/Tempor-ai/sybil/tree/m5-staging) on the m5-staging branch under the /ui directory.
- UI shall be tested using a test deployment of Sybil and SNET, on the UAT machine.

## Wants:
- UI development should support the DAPP sandbox.
- UI development should not need AGIX or AGI tokens to function.
